/**
 * Data Generator — MPLADS Synthetic Dataset
 *
 * Generates reproducible synthetic data via a seeded PRNG.
 * Outputs a massive SQL file (004_seed_data.sql) containing INSERT statements.
 */

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

// Seeded PRNG (Mulberry32)
function mulberry32(a: number) {
  return function() {
    let t = a += 0x6D2B79F5;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  }
}

// Global fixed seed for reproducibility
const SEED = 12345;
const random = mulberry32(SEED);

function randInt(min: number, max: number): number {
  return Math.floor(random() * (max - min + 1)) + min;
}

function randElement<T>(arr: T[]): T {
  return arr[randInt(0, arr.length - 1)] as T;
}

function newId(): string {
  const chars = '0123456789abcdef';
  let s = '';
  for (let i = 0; i < 32; i++) s += chars[randInt(0, 15)];
  return `${s.slice(0, 8)}-${s.slice(8, 12)}-4${s.slice(13, 16)}-a${s.slice(17, 20)}-${s.slice(20, 32)}`;
}

// Data Sets
const DISTRICTS = [
  { name: 'North District', code: 'DIST_101', state: 'Delhi' },
  { name: 'South District', code: 'DIST_102', state: 'Delhi' },
  { name: 'East District', code: 'DIST_103', state: 'Delhi' },
  { name: 'West District', code: 'DIST_104', state: 'Delhi' },
];

const CONSTITUENCIES = [
  { name: 'North Assembly', lgd_code: '201', mp: 'Rajesh Sharma', party: 'BJP' },
  { name: 'South Assembly', lgd_code: '202', mp: 'Sunita Verma', party: 'INC' },
  { name: 'East Assembly', lgd_code: '203', mp: 'Amit Patel', party: 'AAP' },
  { name: 'West Assembly', lgd_code: '204', mp: 'Priya Nair', party: 'Independent' },
];

const AGENCIES = [
  { name: 'Public Works Department (PWD)', type: 'State PWD' },
  { name: 'Rural Development Agency (DRDA)', type: 'DRDA' },
  { name: 'Municipal Corporation', type: 'Urban Local Body' },
  { name: 'Irrigation & Flood Control Dept', type: 'Line Department' }
];

const CATEGORIES = ['EDUCATION', 'HEALTH', 'ROADS', 'WATER', 'SANITATION', 'OTHER'];
const STATUSES = ['PROPOSED', 'APPROVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ON_HOLD'];
const ALERT_SEVERITIES = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW'];
const RULES = [
  'RULE_MPLADS_001_FUNDS_EXCEED',
  'RULE_MPLADS_002_SOCIETY_LIMIT',
  'RULE_MPLADS_003_DELAYED_START',
  'RULE_MPLADS_004_SLOW_PROGRESS'
];

function escapeSql(str: string): string {
  return str.replace(/'/g, "''");
}

function generateData() {
  console.log('Generating synthetic data...');
  const statements: string[] = [];
  statements.push('-- Auto-generated by data-gen/generate.ts');
  statements.push('-- Seed: ' + SEED);
  statements.push('');

  // 1. Districts
  const dIds: Record<string, string> = {};
  for (const d of DISTRICTS) {
    const id = newId();
    dIds[d.name] = id;
    statements.push(`INSERT INTO districts (id, name, state, code, lgd_code) VALUES ('${id}', '${escapeSql(d.name)}', '${escapeSql(d.state)}', '${d.code}', '${d.code}') ON CONFLICT (code) DO NOTHING;`);
  }
  statements.push('');

  // 2. Agencies
  const agencyIds: string[] = [];
  for (const a of AGENCIES) {
    const id = newId();
    agencyIds.push(id);
    const dId = dIds[DISTRICTS[0]!.name]!;
    statements.push(`INSERT INTO agencies (id, district_id, name, type) VALUES ('${id}', '${dId}', '${escapeSql(a.name)}', '${escapeSql(a.type)}') ON CONFLICT (id) DO NOTHING;`);
  }
  statements.push('');

  // 3. Constituencies
  const cIds: Record<string, string> = {};
  for (let idx = 0; idx < CONSTITUENCIES.length; idx++) {
    const c = CONSTITUENCIES[idx]!;
    const id = newId();
    cIds[c.name] = id;
    const dName = DISTRICTS[idx % DISTRICTS.length]!.name;
    const dId = dIds[dName]!;
    statements.push(`INSERT INTO constituencies (id, district_id, name, lgd_code, mp_name, mp_party) VALUES ('${id}', '${dId}', '${escapeSql(c.name)}', '${c.lgd_code}', '${escapeSql(c.mp)}', '${escapeSql(c.party)}') ON CONFLICT (id) DO NOTHING;`);
  }
  statements.push('');

  // 4. Works
  const numWorks = 200;
  const workIds: string[] = [];
  statements.push('-- Works');
  for (let i = 0; i < numWorks; i++) {
    const id = newId();
    workIds.push(id);
    const dName = randElement(DISTRICTS)!.name;
    const cName = randElement(CONSTITUENCIES)!.name;
    const dId = dIds[dName]!;
    const cId = cIds[cName]!;
    const agencyId = randElement(agencyIds)!;
    
    const category = randElement(CATEGORIES);
    const status = randElement(STATUSES);
    const sanctioned_amount = randInt(100000, 5000000);
    const expenditure = status === 'COMPLETED' ? sanctioned_amount : (status === 'IN_PROGRESS' ? randInt(10000, sanctioned_amount) : 0);
    const title = `Work ${i+1}: ${category} Project at Location ${i}`;
    
    statements.push(`INSERT INTO works (id, esakshi_work_id, district_id, constituency_id, agency_id, mp_name, title, description, category, location_name, status, physical_progress_pct, sanctioned_amount, expenditure, sanction_date) VALUES ('${id}', 'ESK-${1000+i}', '${dId}', '${cId}', '${agencyId}', 'Hon. Member of Parliament', '${escapeSql(title)}', 'Synthetic work description', '${category}', 'Location ${i}', '${status}', ${status === 'COMPLETED' ? 100 : randInt(0, 99)}, ${sanctioned_amount}, ${expenditure}, '2025-01-01') ON CONFLICT (id) DO NOTHING;`);
  }
  statements.push('');

  // 5. Alerts
  const numAlerts = 50;
  statements.push('-- Alerts');
  for (let i = 0; i < numAlerts; i++) {
    const id = newId();
    const workId = randElement(workIds)!;
    const ruleId = randElement(RULES)!;
    const severity = randElement(ALERT_SEVERITIES)!;
    const sevRank = severity === 'CRITICAL' ? 1 : severity === 'HIGH' ? 2 : severity === 'MEDIUM' ? 3 : 4;
    const originId = `origin_${i+1}`;
    
    statements.push(`INSERT INTO alerts (id, work_id, rule_id, origin_id, severity, severity_rank, status, in_budget, reason_code, evidence_text) VALUES ('${id}', '${workId}', '${ruleId}', '${originId}', '${severity}', ${sevRank}, 'OPEN', true, 'ANOMALY_DETECTED', 'Automatic anomaly detection flagged this work') ON CONFLICT (work_id, origin_id) DO NOTHING;`);
  }
  statements.push('');

  const __dirname = new URL('.', import.meta.url).pathname;
  const dirPath = process.platform === 'win32' ? __dirname.substring(1).replace(/\//g, '\\') : __dirname;
  const sqlFile = resolve(dirPath, '../supabase/migrations/004_seed_data.sql');
  writeFileSync(sqlFile, statements.join('\n'));
  console.log(`Generated ${sqlFile} successfully.`);
}

generateData();
