import React, { useEffect, useState } from 'react';
import { api } from '../lib/api';
import { StatCard, Card, PageHeader, Button } from '../components/ui';
import { Clock, ShieldAlert, CheckCircle, Zap } from 'lucide-react';
import type { SLAStats } from '../types';

export function SLAPage() {
  const [stats, setStats] = useState<SLAStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [evaluating, setEvaluating] = useState(false);

  const loadData = async () => {
    try {
      setLoading(true);
      const data = await api.sla.stats();
      setStats(data);
    } catch (err) {
      console.error('Failed to load SLA stats:', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadData();
  }, []);

  const handleEvaluate = async () => {
    try {
      setEvaluating(true);
      await api.sla.evaluate();
      await loadData();
    } catch (err) {
      console.error('Failed to evaluate SLA:', err);
    } finally {
      setEvaluating(false);
    }
  };

  return (
    <div className="space-y-8">
      <PageHeader
        title="45-Day SLA Gatekeeping Engine"
        description="Predictive engine to track proposal-to-sanction timelines, forecasting potential breaches and auto-escalating."
        action={
          <Button
            variant="primary"
            onClick={handleEvaluate}
            disabled={evaluating}
            className="glow-primary"
          >
            <Zap className={`w-4 h-4 ${evaluating ? 'animate-spin' : ''}`} />
            {evaluating ? 'Evaluating...' : 'Run SLA Evaluation'}
          </Button>
        }
      />

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <StatCard
          title="Total Proposals"
          value={stats?.total ?? 0}
          subtitle="Works awaiting sanction"
          icon={Clock}
          variant="default"
        />
        <StatCard
          title="Breached (>45 Days)"
          value={stats?.breached ?? 0}
          subtitle="Critical SLA failures"
          icon={ShieldAlert}
          variant={(stats?.breached ?? 0) > 0 ? 'critical' : 'success'}
        />
        <StatCard
          title="At Risk (>35 Days)"
          value={stats?.atRisk ?? 0}
          subtitle="Approaching breach limit"
          icon={Clock}
          variant={(stats?.atRisk ?? 0) > 0 ? 'warning' : 'success'}
        />
        <StatCard
          title="Safe (<35 Days)"
          value={stats?.safe ?? 0}
          subtitle="Within acceptable limits"
          icon={CheckCircle}
          variant="success"
        />
      </div>

      <Card className="p-6">
        <h3 className="text-lg font-semibold text-slate-900 mb-4">SLA Engine Overview</h3>
        <div className="space-y-4 text-slate-500">
          <p>
            The SLA Gatekeeping Engine tracks the timeline from when a work is first proposed (Recommended Date) until it is officially sanctioned by the District Authority.
          </p>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>SLA Limit:</strong> 45 days. Proposals exceeding this limit are automatically flagged as <code>CRITICAL</code>.</li>
            <li><strong>Risk Threshold:</strong> 35 days. Proposals exceeding this limit are flagged as <code>HIGH</code> risk.</li>
            <li><strong>Average Age:</strong> Currently {stats?.avgDays ?? 0} days for active proposals.</li>
          </ul>
          <p className="mt-4">
            Alerts generated by this engine appear in the central Triage Queue for immediate action by District Authorities.
          </p>
        </div>
      </Card>
    </div>
  );
}
