-- MPLADS / DRISHTI — seed data has moved to `supabase/seed.sql`
--
-- This file used to be **written by `data-gen/generate.ts`** on every run. That
-- made a version-controlled migration a build artifact of a data generator: the
-- applied schema history was rewritten whenever the corpus changed, and the diff
-- of a migration could not be told apart from the diff of a dataset.
--
-- Migrations and seeds are different things:
--
--   * A migration is *history*. It is ordered, applied once, and never rewritten
--     — a database that has run 004 must be able to run 005 and reach the same
--     state as a fresh one.
--   * A seed is *current-state data*. It is regenerated whenever the corpus should
--     change, and replacing it wholesale is the normal case.
--
-- The generator now writes `supabase/seed.sql`. Load it after the migrations:
--
--     npm run generate -w data-gen     # rebuild the corpus (note: -w data-gen;
--                                      # there is no root `generate` script)
--     psql "$DATABASE_URL" -f supabase/seed.sql
--
-- This file is kept, rather than deleted, so a database that already applied 004
-- keeps a contiguous migration history. It is intentionally a no-op.
